languageCode = 'en-us'
pagination.pagerSize = 5
title = 'Core Dump'

[outputs]
home = ["HTML", "JSON", "RSS"]

[menu]
main = [
  {identifier = "Books", name = "Books", url = "/books/"},
  {identifier = "Archive", name = "Archive", url = "/archive/"},
  {identifier = "Search", name = "Search", url = "/search/"},
  {identifier = "RSS", name = "RSS", url = "index.xml"},
]

[taxonomies]
tag = 'tags'

[module]
[[module.imports]]
path = "github.com/adityatelange/hugo-PaperMod"

[markup.goldmark.renderer]
unsafe = true

[params]
DateFormat = "2006-01-02"
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
env = "production"
social = true
author = { name = "Athul Suresh" }
footer = { text = "[Source](https://github.com/crunchbang/athulsuresh.com)" }
socialIcons = [
  {name = "github", url = "https://github.com/crunchbang"},
  {name = "rss", url = "index.xml"},
]

[fuseOpts]
distance = 0
igNoreLocation = true
isCaseSensitive = true
keys = ["title", "permalink", "summary", "content"]
limit = 10
minMatchCharLength = 0
shouldSort = true
threshold = 0.0

[params.homeInfoParams]
Content = """
I’m athul (ah-THUL, Malayalam: അതുൽ, Hindi: अतुल), a programmer from a small town in Kerala in the southern part of India.

There is no grand theme tying these posts together. They are mostly anecdotes, experiences, and notes collected over the years while I tinkered with telephony systems, payment platforms, and whatever else held my attention long enough to write down.

Caveat emptor.
  """
Title = "Hello."
