languageCode = 'en-us'
pagination.pagerSize = 5
title = 'Core Dump'

[outputs]
home = ["HTML", "JSON", "RSS"]

[menu]
main = [
  {identifier = "Books", name = "Books", url = "/posts/books/"},
  {identifier = "Archive", name = "Archive", url = "/archive/"},
  {identifier = "Search", name = "Search", url = "/search/"},
  {identifier = "Tabs", name = "Tags", url = "/tags/"},
  {identifier = "RSS", name = "RSS", url = "index.xml"},
  {identifier = "Source", name = "Source", url = "https://github.com/crunchbang/athulsuresh.com"},
]

[taxonomies]
tag = 'tags'

[module]
[[module.imports]]
path = "github.com/adityatelange/hugo-PaperMod"

[markup.goldmark.renderer]
unsafe = true

[params]
DateFormat = "2006-01-02"
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
env = "production"
social = true
socialIcons = [
  {name = "github", url = "https://github.com/crunchbang"},
  {name = "rss", url = "index.xml"},
]

[fuseOpts]
distance = 0
igNoreLocation = true
isCaseSensitive = true
keys = ["title", "permalink", "summary", "content"]
limit = 10
minMatchCharLength = 0
shouldSort = true
threshold = 0.0

[params.homeInfoParams]
Content = """
I'm athul (ah-THUL, Malayalam: അതുൽ, Hindi: अतुल)!


I'm a programmer from a small town in Kerala, in the southern part of India.


There is no grand theme or unifying thread that ties these posts together. They are mostly anecdotes, experiences, and notes that I’ve collected over the years while I tinkered around with telephony systems and payment platforms.

Caveat emptor.
  """
Title = "Hello!"
